feat: 여정 키워드 검색, 조회, 삭제 API 구현
FC-Toy-Project-9/Toy_Project2 pull request #9
Opened 2023-10-25 15:49 UTC by YurimYang

### 개발 내용
1. 여정 키워드 검색 카카오 API 구현 완료
2. 여정 조회 API 구현 완료
3. 여정 삭제 API 구현 완료
4. 여정 조회 API 테스트 완료
5. 여정 삭제 API 테스트 완료
6. 리펙토링(w/주석) 완료

### 추후 논의 내용
- Post에서 예외처리를 하고 넘어오는지 논의해야합니다.

2023-10-25 21:50 UTC, dldmldlsy requested changes

2023-10-25 21:50 UTC, dldmldlsy commented on src/main/java/com/fc/toy_project2/domain/itinerary/controller/ItineraryGetDeleteController.java
> +    @DeleteMapping("/delete")
HTTP 메서드로 DELETE라는 걸 명시해줬기 때문에 url에는 delete(행위)가 안들어가도 될 것같아요! 
REST API 설계 관련 문서 첨부합니당 규칙 4번 참고부탁드려요!
https://devuna.tistory.com/79

2023-10-25 21:54 UTC, dldmldlsy commented on src/main/java/com/fc/toy_project2/domain/itinerary/controller/ItineraryGetDeleteController.java
> +    @GetMapping("/get")
아래와 마찬가지로, 행위는 HTTP 메서드로 나타내고 url에는 자원만 표현하는 것이 더 REST API에 적합하다고 생각합니당! 해당 API에서는 추가로 URL를 적지 않는 게 어떨까요?

2023-10-25 22:13 UTC, YurimYang commented on src/main/java/com/fc/toy_project2/domain/itinerary/controller/ItineraryGetDeleteController.java
> +    @DeleteMapping("/delete")
확인했습니다 !! 아마 get이랑 delete를 안써주면 request param으로 둘다 숫자를 받아줘서 혼동될까봐 적어뒀던 것 같아요 ㅎㅎ 다른 이름으로 수정하도록 하겠습니다 !

2023-10-25 22:13 UTC, YurimYang commented on src/main/java/com/fc/toy_project2/domain/itinerary/controller/ItineraryGetDeleteController.java
> +    @GetMapping("/get")
넵 확인했습니다 !!

2023-10-25 22:30 UTC, dldmldlsy reviewed
늦게까지 수고하셨씁니당 👍😊👍

2023-10-25 22:30 UTC, dldmldlsy commented on src/main/java/com/fc/toy_project2/domain/itinerary/controller/ItineraryGetDeleteController.java
> +    public ResponseEntity<ResponseDTO> deleteItineray(@RequestParam long itineraryId)
RequestParam보다 PathVariable을 사용하는 게 어떨까요?? 
@RequestParam은 선택적인 매개 변수로 사용될 때나 여러 매개 변수가 있을 때 유용한 점이 있고,
@PathVariable은 리소스를 식별하는 데 주로 사용되기때문에 GET이나 DELETE에서 id를 통해 자원을 구분하는 해당 API에는 PathVariable이 더 좋지 않을까 생각합니다! 
https://ryan-han.com/post/translated/pathvariable_queryparam/

사실 RequestParam을 사용해서 문제될 건 전혀 없지만, 이왕이면 팀에서는 상황마다 같은 방식으로 맞추는 게 좋다고 생각하고 이미 merge한 의정님께서 PathVariable 방식으로 사용하셨기 때문에 그렇게 통일하는 게 어떤가 제안드립니당 😊 네이버에서도 블로그글을 구분할 때 해당방식으로 설계했더라구요! 
꼭 필요한 문제는 아니라서 여유되시면 부탁드려용 !

2023-10-25 22:31 UTC, dldmldlsy commented on src/main/java/com/fc/toy_project2/domain/itinerary/controller/ItineraryGetDeleteController.java
> +    @DeleteMapping("/delete")
앗 그래도 HTTP Method가 달라서 괜찮은 걸로 알고 있습니다!!

2023-10-25 22:31 UTC, dldmldlsy commented on src/main/java/com/fc/toy_project2/domain/itinerary/controller/ItineraryGetDeleteController.java
> +    public ResponseEntity<ResponseDTO> deleteItineray(@RequestParam long itineraryId)
ㅠ.ㅠ 수정하고 계실텐데ㅠㅠ 안주무신 줄 알았으면 이거 빨리 올릴 걸 그랬네요 죄송합니당!

2023-10-25 23:10 UTC, YurimYang commented on src/main/java/com/fc/toy_project2/domain/itinerary/controller/ItineraryGetDeleteController.java
> +    public ResponseEntity<ResponseDTO> deleteItineray(@RequestParam long itineraryId)
오,,!! 아닙니다 피드백 너무 감사하죠 ㅎㅎ 
저도 merging 하면서 리펙할 때 어떻게 할지 의논해봐야겠다고 생각했는데 좋습니다 ㅎㅎ 
이부분은 그럼 오늘 회의 거치면서 다른분들과 같이 통일하는 걸로 할까요?

2023-10-26 02:01 UTC, JeongUijeong reviewed
몇 가지 코멘트 달아뒀습니다 🙂

2023-10-26 02:01 UTC, JeongUijeong commented on src/main/java/com/fc/toy_project2/domain/itinerary/controller/ItineraryGetDeleteController.java
> +    @DeleteMapping("")
이런 경우 @DeleteMapping이라고만 하셔도 됩니다!

2023-10-26 02:01 UTC, JeongUijeong commented on src/main/java/com/fc/toy_project2/domain/itinerary/service/ItineraryGetDeleteService.java
> +    public ItineraryGetResponseDTO deleteItinerary(Long itineraryId) throws NotFoundException {
NotFoundException을 throws하실 필요가 없어보이네요!

2023-10-26 02:01 UTC, JeongUijeong commented on src/test/java/com/fc/toy_project2/itinerary/unit/controller/ItineraryRestControllerTest.java
> +            // given, when, then
// given, when, then 이라고 적혀있네요! 위에 적으신 테스트 코드처럼 나눠서 적어주세요ㅎㅎ

2023-10-26 02:34 UTC, YurimYang commented on src/main/java/com/fc/toy_project2/domain/itinerary/service/ItineraryGetDeleteService.java
> +    public ItineraryGetResponseDTO deleteItinerary(Long itineraryId) throws NotFoundException {
넵 ! 이부분은 ItineraryNotFoundException으로 throws 하도록 할게요!

2023-10-26 02:34 UTC, YurimYang commented on src/test/java/com/fc/toy_project2/itinerary/unit/controller/ItineraryRestControllerTest.java
> +            // given, when, then
아 확인했습니다 ~!

2023-10-26 02:47 UTC, YurimYang commented on src/main/java/com/fc/toy_project2/domain/itinerary/controller/ItineraryGetDeleteController.java
> +    @DeleteMapping("")
넵 PathVariable로 바꾸면서 URI를 바꾸도록 하겠습니다 !

2023-10-26 05:17 UTC, JeongUijeong approved these changes

2023-10-26 05:36 UTC, dldmldlsy approved these changes

2023-10-26 05:37 UTC, merged